name: Metadata Action
description: placeholder
branding:
  icon: arrow-right-circle
  color: gray-dark

runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Tag
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ github.repository }}
        tags: |
          type=semver,pattern=v{{major}}

    - name: Push Tag
      shell: bash
      run: |
        branch=$(gh repo view --json defaultBranchRef -q .defaultBranchRef.name)
        tag=${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
        
        git tag -f ${tag}
        git push -d origin ${branch} ${tag} || :
        git push origin HEAD:${branch} tag ${tag}
      env:
        GH_TOKEN: ${{ github.token }}
        
          
